-- Inserir exercicis per defecte a la taula exercises

-- EXERCICIS DE FORÇA (STRENGTH)
INSERT INTO exercises (name, category, muscle_groups, equipment, description, is_default)
VALUES
    -- Pecho
    ('Press de banca', 'strength', ARRAY['pectorals', 'triceps', 'deltoides anteriors'], ARRAY['banca', 'barra', 'discos'], 'Exercici bàsic per desenvolupar el pit', true),
    ('Press inclinat', 'strength', ARRAY['pectorals superiors', 'triceps', 'deltoides anteriors'], ARRAY['banca inclinada', 'barra', 'discos'], 'Variació del press de banca amb banca inclinada', true),
    ('Press declinat', 'strength', ARRAY['pectorals inferiors', 'triceps'], ARRAY['banca declinada', 'barra', 'discos'], 'Variació del press de banca amb banca declinada', true),
    ('Fondos', 'strength', ARRAY['pectorals', 'triceps', 'deltoides anteriors'], ARRAY['barres paral·leles'], 'Exercici amb pes corporal per pit i triceps', true),
    ('Flexions', 'strength', ARRAY['pectorals', 'triceps', 'deltoides anteriors'], ARRAY['cap'], 'Exercici amb pes corporal bàsic', true),
    ('Flexions diamant', 'strength', ARRAY['triceps', 'pectorals'], ARRAY['cap'], 'Variació de flexions enfocada en triceps', true),
    ('Apertures amb mancuernes', 'strength', ARRAY['pectorals'], ARRAY['mancuernes', 'banca'], 'Exercici d''aïllament per pectorals', true),
    ('Crucifixos', 'strength', ARRAY['pectorals'], ARRAY['mancuernes', 'banca'], 'Exercici d''aïllament per pectorals', true),
    
    -- Espalda
    ('Dominades', 'strength', ARRAY['dorsals', 'bíceps', 'deltoides posteriors'], ARRAY['barra de dominades'], 'Exercici amb pes corporal per dorsals', true),
    ('Rem amb barra', 'strength', ARRAY['dorsals', 'romboides', 'bíceps'], ARRAY['barra', 'discos'], 'Exercici bàsic per desenvolupar l''esquena', true),
    ('Rem amb mancuerna', 'strength', ARRAY['dorsals', 'romboides', 'bíceps'], ARRAY['mancuerna', 'banca'], 'Exercici unilateral per dorsals', true),
    ('Jalones al pecho', 'strength', ARRAY['dorsals', 'bíceps'], ARRAY['màquina de polea'], 'Exercici de polea per dorsals', true),
    ('Jalones tras nuca', 'strength', ARRAY['dorsals', 'romboides'], ARRAY['màquina de polea'], 'Variació de jalones', true),
    ('Peso muerto', 'strength', ARRAY['dorsals', 'gluteus', 'cuadriceps', 'isquiotibials'], ARRAY['barra', 'discos'], 'Exercici compost bàsic', true),
    ('Peso muerto rumano', 'strength', ARRAY['isquiotibials', 'gluteus', 'dorsals'], ARRAY['barra', 'discos'], 'Variació del peso muerto', true),
    ('Hiperextensions', 'strength', ARRAY['dorsals inferiors', 'gluteus'], ARRAY['màquina d''hiperextensions'], 'Exercici per dorsals inferiors', true),
    ('Encogimientos', 'strength', ARRAY['trapezis'], ARRAY['mancuernes', 'barra'], 'Exercici per desenvolupar trapezi', true),
    
    -- Hombros
    ('Press militar', 'strength', ARRAY['deltoides', 'triceps'], ARRAY['barra', 'discos'], 'Exercici bàsic per desenvolupar els muscles', true),
    ('Press Arnold', 'strength', ARRAY['deltoides', 'triceps'], ARRAY['mancuernes'], 'Variació del press amb rotació', true),
    ('Elevacions laterals', 'strength', ARRAY['deltoides laterals'], ARRAY['mancuernes'], 'Exercici d''aïllament per deltoides laterals', true),
    ('Elevacions frontals', 'strength', ARRAY['deltoides anteriors'], ARRAY['mancuernes', 'barra'], 'Exercici d''aïllament per deltoides anteriors', true),
    ('Vuelos laterals', 'strength', ARRAY['deltoides posteriors'], ARRAY['mancuernes'], 'Exercici per deltoides posteriors', true),
    ('Pájaros', 'strength', ARRAY['deltoides posteriors', 'romboides'], ARRAY['mancuernes', 'banca inclinada'], 'Exercici per deltoides posteriors', true),
    
    -- Bíceps
    ('Curl de bíceps', 'strength', ARRAY['bíceps'], ARRAY['mancuernes', 'barra'], 'Exercici bàsic per bíceps', true),
    ('Curl martillo', 'strength', ARRAY['bíceps', 'antebrazos'], ARRAY['mancuernes'], 'Variació del curl amb grip neutre', true),
    ('Curl concentrado', 'strength', ARRAY['bíceps'], ARRAY['mancuerna', 'banca'], 'Exercici d''aïllament per bíceps', true),
    ('Curl con barra Z', 'strength', ARRAY['bíceps'], ARRAY['barra Z'], 'Variació del curl amb barra Z', true),
    ('Curl predicador', 'strength', ARRAY['bíceps'], ARRAY['màquina de predicador', 'barra'], 'Exercici d''aïllament per bíceps', true),
    
    -- Tríceps
    ('Extensiones de tríceps', 'strength', ARRAY['triceps'], ARRAY['mancuerna', 'barra'], 'Exercici bàsic per triceps', true),
    ('Fondos en paralelas', 'strength', ARRAY['triceps', 'deltoides anteriors'], ARRAY['barres paral·leles'], 'Exercici amb pes corporal per triceps', true),
    ('Press francés', 'strength', ARRAY['triceps'], ARRAY['barra', 'mancuerna'], 'Exercici d''aïllament per triceps', true),
    ('Extensiones con polea', 'strength', ARRAY['triceps'], ARRAY['màquina de polea'], 'Exercici de polea per triceps', true),
    ('Fondos en banco', 'strength', ARRAY['triceps', 'deltoides anteriors'], ARRAY['banca'], 'Exercici amb pes corporal per triceps', true),
    
    -- Piernas
    ('Sentadillas', 'strength', ARRAY['cuadriceps', 'gluteus', 'isquiotibials'], ARRAY['barra', 'discos'], 'Exercici bàsic per cames', true),
    ('Sentadillas frontales', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Variació de sentadillas amb barra frontal', true),
    ('Prensa', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['màquina de prensa'], 'Exercici de màquina per cames', true),
    ('Zancadas', 'strength', ARRAY['cuadriceps', 'gluteus', 'isquiotibials'], ARRAY['mancuernes', 'barra'], 'Exercici unilateral per cames', true),
    ('Peso muerto', 'strength', ARRAY['isquiotibials', 'gluteus', 'dorsals'], ARRAY['barra', 'discos'], 'Exercici compost per cames posteriors', true),
    ('Extensiones de cuadriceps', 'strength', ARRAY['cuadriceps'], ARRAY['màquina d''extensions'], 'Exercici d''aïllament per cuadriceps', true),
    ('Curl de pierna', 'strength', ARRAY['isquiotibials'], ARRAY['màquina de curl'], 'Exercici d''aïllament per isquiotibials', true),
    ('Elevaciones de talón', 'strength', ARRAY['gemelos'], ARRAY['màquina de gemelos', 'mancuernes'], 'Exercici per desenvolupar els gemelos', true),
    ('Sentadillas búlgaras', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['mancuernes', 'banca'], 'Exercici unilateral avançat', true),
    ('Hip thrust', 'strength', ARRAY['gluteus', 'isquiotibials'], ARRAY['barra', 'discos', 'banca'], 'Exercici per desenvolupar gluteus', true),
    
    -- Abdominales
    ('Abdominales', 'strength', ARRAY['abdominals'], ARRAY['cap'], 'Exercici bàsic per abdominals', true),
    ('Plancha', 'strength', ARRAY['abdominals', 'core'], ARRAY['cap'], 'Exercici isomètric per core', true),
    ('Plancha lateral', 'strength', ARRAY['abdominals laterals', 'core'], ARRAY['cap'], 'Variació de plancha per abdominals laterals', true),
    ('Crunches', 'strength', ARRAY['abdominals superiors'], ARRAY['cap'], 'Exercici per abdominals superiors', true),
    ('Elevaciones de piernas', 'strength', ARRAY['abdominals inferiors'], ARRAY['cap'], 'Exercici per abdominals inferiors', true),
    ('Russian twists', 'strength', ARRAY['abdominals laterals', 'core'], ARRAY['pesa', 'cap'], 'Exercici rotacional per core', true),
    ('Mountain climbers', 'strength', ARRAY['abdominals', 'core', 'cardio'], ARRAY['cap'], 'Exercici dinàmic per core i cardio', true),
    ('Dead bug', 'strength', ARRAY['abdominals', 'core'], ARRAY['cap'], 'Exercici de control del core', true),
    
    -- Antebrazos
    ('Curl de muñeca', 'strength', ARRAY['antebrazos'], ARRAY['barra', 'mancuernes'], 'Exercici per desenvolupar antebrazos', true),
    ('Curl de muñeca inverso', 'strength', ARRAY['antebrazos'], ARRAY['barra', 'mancuernes'], 'Variació del curl de muñeca', true),
    ('Martillo', 'strength', ARRAY['antebrazos', 'bíceps'], ARRAY['mancuernes'], 'Exercici per antebrazos i bíceps', true),
    
    -- Exercicis addicionals de pit
    ('Press de banca amb mancuernes', 'strength', ARRAY['pectorals', 'triceps', 'deltoides anteriors'], ARRAY['mancuernes', 'banca'], 'Variació del press de banca amb mancuernes', true),
    ('Press inclinat amb mancuernes', 'strength', ARRAY['pectorals superiors', 'triceps'], ARRAY['mancuernes', 'banca inclinada'], 'Press inclinat amb mancuernes', true),
    ('Flexions amb palmell', 'strength', ARRAY['pectorals', 'triceps'], ARRAY['cap'], 'Variació de flexions amb palmell elevat', true),
    ('Flexions declinades', 'strength', ARRAY['pectorals superiors', 'triceps'], ARRAY['cap'], 'Flexions amb peus elevats', true),
    ('Pullover', 'strength', ARRAY['pectorals', 'dorsals', 'triceps'], ARRAY['mancuerna', 'banca'], 'Exercici per pectorals i dorsals', true),
    ('Press de banca amb grip tancat', 'strength', ARRAY['triceps', 'pectorals'], ARRAY['barra', 'discos'], 'Variació enfocada en triceps', true),
    
    -- Exercicis addicionals d'esquena
    ('Rem T', 'strength', ARRAY['dorsals', 'romboides', 'deltoides posteriors'], ARRAY['barra T'], 'Exercici amb barra T per dorsals', true),
    ('Rem amb cable', 'strength', ARRAY['dorsals', 'romboides', 'bíceps'], ARRAY['màquina de cable'], 'Exercici de cable per dorsals', true),
    ('Rem invertit', 'strength', ARRAY['dorsals', 'romboides', 'deltoides posteriors'], ARRAY['barra', 'cap'], 'Exercici amb pes corporal per dorsals', true),
    ('Pull-ups', 'strength', ARRAY['dorsals', 'bíceps', 'deltoides posteriors'], ARRAY['barra de dominades'], 'Variació de dominades', true),
    ('Chin-ups', 'strength', ARRAY['bíceps', 'dorsals'], ARRAY['barra de dominades'], 'Dominades amb grip supí', true),
    ('Rem un brazo con cable', 'strength', ARRAY['dorsals', 'romboides'], ARRAY['màquina de cable'], 'Exercici unilateral amb cable', true),
    ('Good mornings', 'strength', ARRAY['isquiotibials', 'gluteus', 'dorsals'], ARRAY['barra', 'discos'], 'Exercici per cames posteriors i esquena', true),
    ('Superman', 'strength', ARRAY['dorsals inferiors', 'gluteus'], ARRAY['cap'], 'Exercici amb pes corporal per dorsals inferiors', true),
    
    -- Exercicis addicionals d'hombres
    ('Press de hombro amb mancuernes', 'strength', ARRAY['deltoides', 'triceps'], ARRAY['mancuernes'], 'Press de muscles amb mancuernes', true),
    ('Press de hombro sentado', 'strength', ARRAY['deltoides', 'triceps'], ARRAY['mancuernes', 'banca'], 'Press de muscles en posició asseguda', true),
    ('Elevacions laterals amb cable', 'strength', ARRAY['deltoides laterals'], ARRAY['màquina de cable'], 'Elevacions laterals amb cable', true),
    ('Elevacions frontals amb cable', 'strength', ARRAY['deltoides anteriors'], ARRAY['màquina de cable'], 'Elevacions frontals amb cable', true),
    ('Face pulls', 'strength', ARRAY['deltoides posteriors', 'romboides'], ARRAY['màquina de cable'], 'Exercici per deltoides posteriors', true),
    ('Shrugs', 'strength', ARRAY['trapezis'], ARRAY['mancuernes', 'barra'], 'Exercici per desenvolupar trapezi', true),
    ('Upright row', 'strength', ARRAY['deltoides', 'trapezis'], ARRAY['barra', 'mancuernes'], 'Rem vertical per muscles i trapezi', true),
    
    -- Exercicis addicionals de bíceps
    ('Curl de bíceps amb barra recta', 'strength', ARRAY['bíceps'], ARRAY['barra recta', 'discos'], 'Curl amb barra recta', true),
    ('Curl de bíceps alternado', 'strength', ARRAY['bíceps'], ARRAY['mancuernes'], 'Curl alternant braços', true),
    ('Curl de bíceps 21', 'strength', ARRAY['bíceps'], ARRAY['barra', 'discos'], 'Tècnica especial de curl', true),
    ('Curl de bíceps en banco Scott', 'strength', ARRAY['bíceps'], ARRAY['màquina Scott', 'barra'], 'Exercici d''aïllament en banco Scott', true),
    ('Curl de bíceps con cable', 'strength', ARRAY['bíceps'], ARRAY['màquina de cable'], 'Curl amb cable', true),
    ('Curl de bíceps en polea alta', 'strength', ARRAY['bíceps'], ARRAY['màquina de polea'], 'Curl amb polea alta', true),
    
    -- Exercicis addicionals de tríceps
    ('Extensiones de tríceps sobre cabeza', 'strength', ARRAY['triceps'], ARRAY['mancuerna'], 'Extensiones per sobre del cap', true),
    ('Extensiones de tríceps con cable', 'strength', ARRAY['triceps'], ARRAY['màquina de cable'], 'Extensiones amb cable', true),
    ('Extensiones de tríceps con cuerda', 'strength', ARRAY['triceps'], ARRAY['màquina de cable', 'corda'], 'Extensiones amb corda', true),
    ('Dips', 'strength', ARRAY['triceps', 'pectorals', 'deltoides anteriors'], ARRAY['barres paral·leles'], 'Fondos per triceps i pit', true),
    ('Kickbacks', 'strength', ARRAY['triceps'], ARRAY['mancuerna', 'banca'], 'Extensiones de triceps en posició inclinada', true),
    ('Extensiones de tríceps con barra', 'strength', ARRAY['triceps'], ARRAY['barra', 'discos'], 'Extensiones amb barra', true),
    
    -- Exercicis addicionals de cames
    ('Sentadillas sumo', 'strength', ARRAY['cuadriceps', 'gluteus', 'adductors'], ARRAY['barra', 'discos'], 'Sentadillas amb posició ampla', true),
    ('Sentadillas goblet', 'strength', ARRAY['cuadriceps', 'gluteus', 'core'], ARRAY['mancuerna', 'pesa'], 'Sentadillas amb pesa davant', true),
    ('Sentadillas con salto', 'strength', ARRAY['cuadriceps', 'gluteus', 'cardio'], ARRAY['cap'], 'Sentadillas amb salt explosiu', true),
    ('Prensa inclinada', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['màquina de prensa'], 'Prensa en posició inclinada', true),
    ('Prensa horizontal', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['màquina de prensa'], 'Prensa en posició horitzontal', true),
    ('Zancadas caminando', 'strength', ARRAY['cuadriceps', 'gluteus', 'isquiotibials'], ARRAY['mancuernes'], 'Zancadas caminant', true),
    ('Zancadas laterales', 'strength', ARRAY['cuadriceps', 'gluteus', 'adductors'], ARRAY['mancuernes'], 'Zancadas laterals', true),
    ('Pistol squat', 'strength', ARRAY['cuadriceps', 'gluteus', 'core'], ARRAY['cap'], 'Sentadilla amb una cama', true),
    ('Wall sit', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['cap'], 'Exercici isomètric contra la paret', true),
    ('Leg press', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['màquina de prensa'], 'Prensa de cames', true),
    ('Hack squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['màquina hack squat'], 'Sentadillas en màquina hack', true),
    ('Sissy squat', 'strength', ARRAY['cuadriceps'], ARRAY['cap'], 'Variació avançada de sentadillas', true),
    ('Curl de pierna tumbado', 'strength', ARRAY['isquiotibials'], ARRAY['màquina de curl'], 'Curl de cama en posició tumbada', true),
    ('Curl de pierna sentado', 'strength', ARRAY['isquiotibials'], ARRAY['màquina de curl'], 'Curl de cama en posició asseguda', true),
    ('Curl de pierna de pie', 'strength', ARRAY['isquiotibials'], ARRAY['màquina de curl'], 'Curl de cama dempeus', true),
    ('Peso muerto con mancuernas', 'strength', ARRAY['isquiotibials', 'gluteus', 'dorsals'], ARRAY['mancuernes'], 'Peso muerto amb mancuernes', true),
    ('Peso muerto sumo', 'strength', ARRAY['gluteus', 'adductors', 'isquiotibials'], ARRAY['barra', 'discos'], 'Peso muerto amb posició ampla', true),
    ('Elevaciones de gemelos sentado', 'strength', ARRAY['gemelos'], ARRAY['màquina de gemelos'], 'Elevacions de gemelos assegut', true),
    ('Elevaciones de gemelos de pie', 'strength', ARRAY['gemelos'], ARRAY['màquina de gemelos'], 'Elevacions de gemelos dempeus', true),
    ('Elevaciones de gemelos con mancuerna', 'strength', ARRAY['gemelos'], ARRAY['mancuerna'], 'Elevacions amb mancuerna', true),
    ('Calf raise', 'strength', ARRAY['gemelos'], ARRAY['màquina de gemelos'], 'Elevacions de gemelos', true),
    ('Step ups', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['caixa', 'mancuernes'], 'Pujades a caixa', true),
    ('Lunges', 'strength', ARRAY['cuadriceps', 'gluteus', 'isquiotibials'], ARRAY['mancuernes'], 'Zancadas', true),
    
    -- Exercicis addicionals d'abdominals
    ('Abdominales oblicuos', 'strength', ARRAY['abdominals laterals'], ARRAY['cap'], 'Abdominals per laterals', true),
    ('Bicycle crunches', 'strength', ARRAY['abdominals', 'core'], ARRAY['cap'], 'Abdominals en bicicleta', true),
    ('Leg raises', 'strength', ARRAY['abdominals inferiors'], ARRAY['cap'], 'Elevacions de cames', true),
    ('Hanging leg raises', 'strength', ARRAY['abdominals inferiors', 'core'], ARRAY['barra de dominades'], 'Elevacions de cames penjat', true),
    ('Crunches con piernas elevadas', 'strength', ARRAY['abdominals superiors'], ARRAY['cap'], 'Crunches amb cames elevades', true),
    ('V-ups', 'strength', ARRAY['abdominals', 'core'], ARRAY['cap'], 'Exercici en forma de V', true),
    ('Toes to bar', 'strength', ARRAY['abdominals', 'core'], ARRAY['barra de dominades'], 'Exercici avançat de core', true),
    ('L-sit', 'strength', ARRAY['abdominals', 'core', 'triceps'], ARRAY['barres paral·leles'], 'Exercici isomètric avançat', true),
    ('Dragon flag', 'strength', ARRAY['abdominals', 'core'], ARRAY['banca'], 'Exercici avançat de core', true),
    ('Ab wheel', 'strength', ARRAY['abdominals', 'core'], ARRAY['roda abdominal'], 'Exercici amb roda abdominal', true),
    ('Sit-ups', 'strength', ARRAY['abdominals superiors'], ARRAY['cap'], 'Abdominals tradicionals', true),
    ('Flutter kicks', 'strength', ARRAY['abdominals inferiors', 'core'], ARRAY['cap'], 'Patades ràpides', true),
    ('Scissor kicks', 'strength', ARRAY['abdominals inferiors', 'core'], ARRAY['cap'], 'Patades de tisora', true),
    ('Reverse crunches', 'strength', ARRAY['abdominals inferiors'], ARRAY['cap'], 'Crunches inversos', true),
    ('Side planks', 'strength', ARRAY['abdominals laterals', 'core'], ARRAY['cap'], 'Plancha lateral', true),
    ('Plank con elevación de pierna', 'strength', ARRAY['abdominals', 'core', 'gluteus'], ARRAY['cap'], 'Plancha amb elevació de cama', true),
    ('Plank con elevación de brazo', 'strength', ARRAY['abdominals', 'core'], ARRAY['cap'], 'Plancha amb elevació de braç', true),
    ('Bear crawl', 'strength', ARRAY['abdominals', 'core', 'cames', 'braços'], ARRAY['cap'], 'Desplaçament en posició d''ós', true),
    
    -- Exercicis compostos addicionals
    ('Thruster', 'strength', ARRAY['cuadriceps', 'gluteus', 'deltoides', 'triceps'], ARRAY['mancuernes', 'barra'], 'Exercici compost complet', true),
    ('Clean and press', 'strength', ARRAY['cames', 'dorsals', 'deltoides', 'triceps'], ARRAY['barra', 'discos'], 'Exercici olímpic compost', true),
    ('Snatch', 'strength', ARRAY['cames', 'dorsals', 'deltoides', 'core'], ARRAY['barra', 'discos'], 'Exercici olímpic avançat', true),
    ('Turkish get-up', 'strength', ARRAY['core', 'deltoides', 'cames'], ARRAY['pesa', 'mancuerna'], 'Exercici funcional complet', true),
    ('Farmers walk', 'strength', ARRAY['trapezis', 'core', 'antebrazos'], ARRAY['mancuernes', 'peses'], 'Caminar amb peses', true),
    ('Suitcase carry', 'strength', ARRAY['core', 'trapezis'], ARRAY['mancuerna', 'pesa'], 'Portar pesa lateral', true),
    
    -- CARDIO
    ('Cinta de correr', 'cardio', ARRAY['cardio'], ARRAY['cinta de correr'], 'Exercici cardiovascular en cinta', true),
    ('Bicicleta estática', 'cardio', ARRAY['cardio', 'cuadriceps'], ARRAY['bicicleta estática'], 'Exercici cardiovascular en bicicleta', true),
    ('Elíptica', 'cardio', ARRAY['cardio', 'cames', 'braços'], ARRAY['elíptica'], 'Exercici cardiovascular en elíptica', true),
    ('Remo', 'cardio', ARRAY['cardio', 'dorsals', 'cames'], ARRAY['màquina de remo'], 'Exercici cardiovascular de remo', true),
    ('Escaladora', 'cardio', ARRAY['cardio', 'cames', 'gluteus'], ARRAY['escaladora'], 'Exercici cardiovascular en escaladora', true),
    ('Burpees', 'cardio', ARRAY['cardio', 'cames', 'braços', 'core'], ARRAY['cap'], 'Exercici cardiovascular amb pes corporal', true),
    ('Jumping jacks', 'cardio', ARRAY['cardio', 'cames'], ARRAY['cap'], 'Exercici cardiovascular bàsic', true),
    ('High knees', 'cardio', ARRAY['cardio', 'cuadriceps'], ARRAY['cap'], 'Exercici cardiovascular dinàmic', true),
    ('Skipping', 'cardio', ARRAY['cardio', 'cames'], ARRAY['cap'], 'Exercici cardiovascular de salt', true),
    
    -- FLEXIBILITAT
    ('Estiramientos de cuadriceps', 'flexibility', ARRAY['cuadriceps'], ARRAY['cap'], 'Estiraments per cuadriceps', true),
    ('Estiramientos de isquiotibiales', 'flexibility', ARRAY['isquiotibials'], ARRAY['cap'], 'Estiraments per isquiotibials', true),
    ('Estiramientos de gemelos', 'flexibility', ARRAY['gemelos'], ARRAY['cap'], 'Estiraments per gemelos', true),
    ('Estiramientos de espalda', 'flexibility', ARRAY['dorsals', 'lumbars'], ARRAY['cap'], 'Estiraments per esquena', true),
    ('Estiramientos de pecho', 'flexibility', ARRAY['pectorals'], ARRAY['cap'], 'Estiraments per pectorals', true),
    ('Estiramientos de hombros', 'flexibility', ARRAY['deltoides'], ARRAY['cap'], 'Estiraments per muscles', true),
    ('Yoga', 'flexibility', ARRAY['flexibilitat general', 'core'], ARRAY['estera'], 'Pràctica de yoga per flexibilitat', true),
    ('Pilates', 'flexibility', ARRAY['core', 'flexibilitat'], ARRAY['estera'], 'Pràctica de pilates', true),
    
    -- ESPORTS
    ('Fútbol', 'sport', ARRAY['cardio', 'cames', 'core'], ARRAY['pilota'], 'Esport de pilota', true),
    ('Baloncesto', 'sport', ARRAY['cardio', 'cames', 'braços'], ARRAY['pilota de bàsquet'], 'Esport de pilota', true),
    ('Tenis', 'sport', ARRAY['cardio', 'cames', 'braços', 'core'], ARRAY['raqueta', 'pilota'], 'Esport de raqueta', true),
    ('Pádel', 'sport', ARRAY['cardio', 'cames', 'braços'], ARRAY['raqueta', 'pilota'], 'Esport de raqueta', true),
    ('Natación', 'sport', ARRAY['cardio', 'cames', 'braços', 'core'], ARRAY['piscina'], 'Esport aquàtic', true),
    ('Ciclismo', 'sport', ARRAY['cardio', 'cuadriceps', 'gluteus'], ARRAY['bicicleta'], 'Esport de ciclisme', true),
    ('Running', 'sport', ARRAY['cardio', 'cames'], ARRAY['cap'], 'Esport de córrer', true),
    ('Atletismo', 'sport', ARRAY['cardio', 'cames', 'velocitat'], ARRAY['cap'], 'Esport d''atletisme', true),
    
    -- Més exercicis de força específics
    ('Landmine press', 'strength', ARRAY['deltoides', 'triceps', 'core'], ARRAY['barra', 'discos'], 'Press amb landmine', true),
    ('Landmine row', 'strength', ARRAY['dorsals', 'romboides'], ARRAY['barra', 'discos'], 'Rem amb landmine', true),
    ('Landmine squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadillas amb landmine', true),
    ('Landmine lunge', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Zancadas amb landmine', true),
    ('Landmine deadlift', 'strength', ARRAY['isquiotibials', 'gluteus'], ARRAY['barra', 'discos'], 'Peso muerto amb landmine', true),
    ('Landmine rotation', 'strength', ARRAY['core', 'deltoides'], ARRAY['barra', 'discos'], 'Rotació amb landmine', true),
    ('Landmine RDL', 'strength', ARRAY['isquiotibials', 'gluteus'], ARRAY['barra', 'discos'], 'Peso muerto rumano amb landmine', true),
    ('Landmine high pull', 'strength', ARRAY['dorsals', 'deltoides'], ARRAY['barra', 'discos'], 'High pull amb landmine', true),
    ('Landmine twist', 'strength', ARRAY['core', 'deltoides'], ARRAY['barra', 'discos'], 'Torsió amb landmine', true),
    ('Landmine single arm press', 'strength', ARRAY['deltoides', 'core'], ARRAY['barra', 'discos'], 'Press unilateral amb landmine', true),
    ('Landmine T-bar row', 'strength', ARRAY['dorsals', 'romboides'], ARRAY['barra', 'discos'], 'Rem T amb landmine', true),
    ('Landmine squat to press', 'strength', ARRAY['cames', 'deltoides'], ARRAY['barra', 'discos'], 'Sentadilla a press amb landmine', true),
    ('Landmine lateral raise', 'strength', ARRAY['deltoides laterals'], ARRAY['barra', 'discos'], 'Elevació lateral amb landmine', true),
    ('Landmine wood chop', 'strength', ARRAY['core', 'deltoides'], ARRAY['barra', 'discos'], 'Tall de llenya amb landmine', true),
    ('Landmine reverse lunge', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Zancada inversa amb landmine', true),
    ('Landmine single leg RDL', 'strength', ARRAY['isquiotibials', 'gluteus', 'core'], ARRAY['barra', 'discos'], 'Peso muerto amb una cama amb landmine', true),
    ('Landmine bent over row', 'strength', ARRAY['dorsals', 'romboides'], ARRAY['barra', 'discos'], 'Rem inclinat amb landmine', true),
    ('Landmine upright row', 'strength', ARRAY['deltoides', 'trapezis'], ARRAY['barra', 'discos'], 'Rem vertical amb landmine', true),
    ('Landmine chest press', 'strength', ARRAY['pectorals', 'triceps'], ARRAY['barra', 'discos'], 'Press de pit amb landmine', true),
    ('Landmine fly', 'strength', ARRAY['pectorals'], ARRAY['barra', 'discos'], 'Vuelos amb landmine', true),
    ('Landmine tricep extension', 'strength', ARRAY['triceps'], ARRAY['barra', 'discos'], 'Extensió de triceps amb landmine', true),
    ('Landmine bicep curl', 'strength', ARRAY['bíceps'], ARRAY['barra', 'discos'], 'Curl de bíceps amb landmine', true),
    ('Landmine shoulder press', 'strength', ARRAY['deltoides', 'triceps'], ARRAY['barra', 'discos'], 'Press de muscles amb landmine', true),
    ('Landmine reverse fly', 'strength', ARRAY['deltoides posteriors'], ARRAY['barra', 'discos'], 'Vuelos posteriors amb landmine', true),
    ('Landmine squat jump', 'strength', ARRAY['cuadriceps', 'gluteus', 'explosivitat'], ARRAY['barra', 'discos'], 'Salt de sentadilla amb landmine', true),
    ('Landmine deadlift row', 'strength', ARRAY['dorsals', 'isquiotibials'], ARRAY['barra', 'discos'], 'Peso muerto a rem amb landmine', true),
    ('Landmine lateral lunge', 'strength', ARRAY['cuadriceps', 'gluteus', 'adductors'], ARRAY['barra', 'discos'], 'Zancada lateral amb landmine', true),
    ('Landmine single arm squat', 'strength', ARRAY['cuadriceps', 'gluteus', 'core'], ARRAY['barra', 'discos'], 'Sentadilla unilateral amb landmine', true),
    ('Landmine good morning', 'strength', ARRAY['isquiotibials', 'gluteus'], ARRAY['barra', 'discos'], 'Good morning amb landmine', true),
    ('Landmine Romanian deadlift', 'strength', ARRAY['isquiotibials', 'gluteus'], ARRAY['barra', 'discos'], 'Peso muerto rumano amb landmine', true),
    ('Landmine sumo deadlift', 'strength', ARRAY['gluteus', 'adductors'], ARRAY['barra', 'discos'], 'Peso muerto sumo amb landmine', true),
    ('Landmine front squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla frontal amb landmine', true),
    ('Landmine overhead squat', 'strength', ARRAY['cuadriceps', 'gluteus', 'core'], ARRAY['barra', 'discos'], 'Sentadilla per sobre del cap amb landmine', true),
    ('Landmine hack squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla hack amb landmine', true),
    ('Landmine Bulgarian split squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla búlgara amb landmine', true),
    ('Landmine Cossack squat', 'strength', ARRAY['cuadriceps', 'gluteus', 'adductors'], ARRAY['barra', 'discos'], 'Sentadilla cosaca amb landmine', true),
    ('Landmine Jefferson deadlift', 'strength', ARRAY['gluteus', 'isquiotibials'], ARRAY['barra', 'discos'], 'Peso muerto Jefferson amb landmine', true),
    ('Landmine suitcase deadlift', 'strength', ARRAY['gluteus', 'core'], ARRAY['barra', 'discos'], 'Peso muerto maleta amb landmine', true),
    ('Landmine single leg deadlift', 'strength', ARRAY['isquiotibials', 'gluteus', 'core'], ARRAY['barra', 'discos'], 'Peso muerto amb una cama amb landmine', true),
    ('Landmine deficit deadlift', 'strength', ARRAY['isquiotibials', 'gluteus'], ARRAY['barra', 'discos'], 'Peso muerto amb dèficit amb landmine', true),
    ('Landmine rack pull', 'strength', ARRAY['dorsals', 'trapezis'], ARRAY['barra', 'discos'], 'Rack pull amb landmine', true),
    ('Landmine snatch', 'strength', ARRAY['cames', 'dorsals', 'deltoides'], ARRAY['barra', 'discos'], 'Arrancada amb landmine', true),
    ('Landmine clean', 'strength', ARRAY['cames', 'dorsals'], ARRAY['barra', 'discos'], 'Cargada amb landmine', true),
    ('Landmine clean and press', 'strength', ARRAY['cames', 'dorsals', 'deltoides'], ARRAY['barra', 'discos'], 'Cargada i press amb landmine', true),
    ('Landmine clean and jerk', 'strength', ARRAY['cames', 'dorsals', 'deltoides'], ARRAY['barra', 'discos'], 'Cargada i enviat amb landmine', true),
    ('Landmine thruster', 'strength', ARRAY['cuadriceps', 'deltoides'], ARRAY['barra', 'discos'], 'Thruster amb landmine', true),
    ('Landmine turkish get-up', 'strength', ARRAY['core', 'deltoides', 'cames'], ARRAY['barra', 'discos'], 'Turkish get-up amb landmine', true),
    ('Landmine windmill', 'strength', ARRAY['core', 'deltoides'], ARRAY['barra', 'discos'], 'Molí de vent amb landmine', true),
    ('Landmine suitcase carry', 'strength', ARRAY['core', 'trapezis'], ARRAY['barra', 'discos'], 'Portar maleta amb landmine', true),
    ('Landmine farmer''s walk', 'strength', ARRAY['trapezis', 'core'], ARRAY['barra', 'discos'], 'Caminar amb peses amb landmine', true),
    ('Landmine waiter''s walk', 'strength', ARRAY['deltoides', 'core'], ARRAY['barra', 'discos'], 'Caminar de cambrer amb landmine', true),
    ('Landmine overhead carry', 'strength', ARRAY['deltoides', 'core'], ARRAY['barra', 'discos'], 'Portar per sobre del cap amb landmine', true),
    ('Landmine front carry', 'strength', ARRAY['core', 'deltoides'], ARRAY['barra', 'discos'], 'Portar frontal amb landmine', true),
    ('Landmine back carry', 'strength', ARRAY['dorsals', 'core'], ARRAY['barra', 'discos'], 'Portar posterior amb landmine', true),
    ('Landmine side carry', 'strength', ARRAY['core', 'deltoides'], ARRAY['barra', 'discos'], 'Portar lateral amb landmine', true),
    ('Landmine cross carry', 'strength', ARRAY['core', 'deltoides'], ARRAY['barra', 'discos'], 'Portar creuat amb landmine', true),
    ('Landmine diagonal carry', 'strength', ARRAY['core', 'deltoides'], ARRAY['barra', 'discos'], 'Portar diagonal amb landmine', true),
    ('Landmine rotational carry', 'strength', ARRAY['core', 'deltoides'], ARRAY['barra', 'discos'], 'Portar rotacional amb landmine', true),
    ('Landmine walking lunge', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Zancadas caminant amb landmine', true),
    ('Landmine reverse walking lunge', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Zancadas inverses caminant amb landmine', true),
    ('Landmine lateral walking lunge', 'strength', ARRAY['cuadriceps', 'gluteus', 'adductors'], ARRAY['barra', 'discos'], 'Zancadas laterals caminant amb landmine', true),
    ('Landmine curtsy lunge', 'strength', ARRAY['gluteus', 'adductors'], ARRAY['barra', 'discos'], 'Zancada de reverència amb landmine', true),
    ('Landmine clock lunges', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Zancadas en rellotge amb landmine', true),
    ('Landmine curtsey lunge', 'strength', ARRAY['gluteus', 'adductors'], ARRAY['barra', 'discos'], 'Zancada de reverència amb landmine', true),
    ('Landmine pistol squat', 'strength', ARRAY['cuadriceps', 'gluteus', 'core'], ARRAY['barra', 'discos'], 'Sentadilla amb una cama amb landmine', true),
    ('Landmine skater squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla de patinador amb landmine', true),
    ('Landmine shrimp squat', 'strength', ARRAY['cuadriceps', 'gluteus', 'core'], ARRAY['barra', 'discos'], 'Sentadilla de gamba amb landmine', true),
    ('Landmine sissy squat', 'strength', ARRAY['cuadriceps'], ARRAY['barra', 'discos'], 'Sentadilla sissy amb landmine', true),
    ('Landmine wall sit', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos', 'paret'], 'Wall sit amb landmine', true),
    ('Landmine calf raise', 'strength', ARRAY['gemelos'], ARRAY['barra', 'discos'], 'Elevacions de gemelos amb landmine', true),
    ('Landmine single leg calf raise', 'strength', ARRAY['gemelos'], ARRAY['barra', 'discos'], 'Elevacions de gemelos amb una cama amb landmine', true),
    ('Landmine seated calf raise', 'strength', ARRAY['gemelos'], ARRAY['barra', 'discos'], 'Elevacions de gemelos assegut amb landmine', true),
    ('Landmine standing calf raise', 'strength', ARRAY['gemelos'], ARRAY['barra', 'discos'], 'Elevacions de gemelos dempeus amb landmine', true),
    ('Landmine donkey calf raise', 'strength', ARRAY['gemelos'], ARRAY['barra', 'discos'], 'Elevacions de gemelos d''ase amb landmine', true),
    ('Landmine barbell hack squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla hack amb barra amb landmine', true),
    ('Landmine Zercher squat', 'strength', ARRAY['cuadriceps', 'gluteus', 'core'], ARRAY['barra', 'discos'], 'Sentadilla Zercher amb landmine', true),
    ('Landmine Anderson squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla Anderson amb landmine', true),
    ('Landmine pause squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla amb pausa amb landmine', true),
    ('Landmine tempo squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla amb tempo amb landmine', true),
    ('Landmine 1.5 squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla 1.5 amb landmine', true),
    ('Landmine jump squat', 'strength', ARRAY['cuadriceps', 'gluteus', 'explosivitat'], ARRAY['barra', 'discos'], 'Salt de sentadilla amb landmine', true),
    ('Landmine box squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos', 'caixa'], 'Sentadilla amb caixa amb landmine', true),
    ('Landmine pin squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla pin amb landmine', true),
    ('Landmine cambered bar squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla amb barra cambered amb landmine', true),
    ('Landmine safety bar squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla amb barra de seguretat amb landmine', true),
    ('Landmine buffalo bar squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla amb barra búfalo amb landmine', true),
    ('Landmine SSB squat', 'strength', ARRAY['cuadriceps', 'gluteus'], ARRAY['barra', 'discos'], 'Sentadilla SSB amb landmine', true),
    ('Landmine front squat to press', 'strength', ARRAY['cuadriceps', 'deltoides'], ARRAY['barra', 'discos'], 'Sentadilla frontal a press amb landmine', true),
    ('Landmine back squat to press', 'strength', ARRAY['cuadriceps', 'deltoides'], ARRAY['barra', 'discos'], 'Sentadilla posterior a press amb landmine', true),
    ('Landmine overhead squat to press', 'strength', ARRAY['cuadriceps', 'deltoides', 'core'], ARRAY['barra', 'discos'], 'Sentadilla per sobre del cap a press amb landmine', true),
    ('Landmine goblet squat to press', 'strength', ARRAY['cuadriceps', 'deltoides'], ARRAY['barra', 'discos'], 'Sentadilla goblet a press amb landmine', true),
    ('Landmine Zercher squat to press', 'strength', ARRAY['cuadriceps', 'deltoides', 'core'], ARRAY['barra', 'discos'], 'Sentadilla Zercher a press amb landmine', true),
    ('Landmine front squat to overhead press', 'strength', ARRAY['cuadriceps', 'deltoides'], ARRAY['barra', 'discos'], 'Sentadilla frontal a press per sobre del cap amb landmine', true),
    ('Landmine back squat to overhead press', 'strength', ARRAY['cuadriceps', 'deltoides'], ARRAY['barra', 'discos'], 'Sentadilla posterior a press per sobre del cap amb landmine', true),
    ('Landmine overhead squat to overhead press', 'strength', ARRAY['cuadriceps', 'deltoides', 'core'], ARRAY['barra', 'discos'], 'Sentadilla per sobre del cap a press per sobre del cap amb landmine', true),
    ('Landmine goblet squat to overhead press', 'strength', ARRAY['cuadriceps', 'deltoides'], ARRAY['barra', 'discos'], 'Sentadilla goblet a press per sobre del cap amb landmine', true),
    ('Landmine Zercher squat to overhead press', 'strength', ARRAY['cuadriceps', 'deltoides', 'core'], ARRAY['barra', 'discos'], 'Sentadilla Zercher a press per sobre del cap amb landmine', true);

